name: x
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.9
  - pip
  - autograd>=1.3
  - fastcore
  - ipykernel
  - jax
  - jaxlib
  - matplotlib>=3.0.3
  - nbdev<2
  - nbstripout
  - numpy>=1.16.2
  - openssl
  - papermill
  - pre-commit
  - maturin
  - rsync
  - scikit-image
  - scipy
  - pip:
    - git+https://github.com/fancompute/ceviche
    - pymkl>=0.0.3
    - -e .
